# Generated by Django 3.1.4 on 2021-03-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210301_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
