# Generated by Django 3.1.4 on 2021-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateField(),
        ),
    ]
