# Generated by Django 3.1.4 on 2021-03-03 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 22, 41, 45, 53408, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 3, 22, 42, 4, 985576, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
