# Generated by Django 3.1.4 on 2021-03-03 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210303_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9:00 AM', '9:00 AM'), ('10:00 AM', '9:00 AM'), ('11:00 AM', '9:00 AM'), ('12:00 PM', '12:00 PM'), ('12:00 PM', '12:00 PM'), ('1:00 PM', '1:00 PM'), ('2:00 PM', '2:00 PM'), ('3:00 PM', '3:00 PM')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
